#!/usr/bin/python3
# -*- coding: utf-8 -*-

import subprocess
import time
import os

## CONFIGURATION ##
possible_mountpoints = ['/','/boot','/root','/home']
before_empty_lines = 0
after_empty_lines = 2
lines_format = '{leader_spaces}\033[1m{desc}\033[0m  {value}'

# Environment variables:
try:
	friendly_name = os.environ['NOTF_FRIENDLY_NAME']
except KeyError:
	friendly_name = ''

try:
	part_mountpoints = os.environ['NOTF_MOUNTPOINTS'] # for example: "/:/boot:/home"
except KeyError:
	part_mountpoints = ''

## FUNCTIONS ##

def binary_prefix(b, bit=False, dec_prefix=False):
	pass

def format_percent(n, digits=0, term_color=False): # n <-- float(0.43)
	pass

def kilo_to_byte(n):
	pass

def sec_to_dhms(n, short=True):
	pass